#连接数据库
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/crm
    username: root
    password: root
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB

  #邮箱验证
  mail:
    protocol: smtps
    host: smtp.163.com
    username: liudaihua68@163.com
    password: FPIXQYSBLUTSIIQG
    port: 465
    default-encoding: UTF-8
#文件上传
files:
  upload:
    path: D:\soft\idea\source\files\



#端口号
server:
  port: 8888

#日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
